[package]
name = "executor"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
serde = { package = "serde", version = "1.0",  features = ["derive"] }
serde_json = "1.0"
itertools = "0.9"

filter = { path = "../filter" }
