[workspace]
members = [
    "executor",
    "filter",
    "icon",
    "maple_cli",
    "matcher",
    "matcher/extracted_fzy",
    "pattern",
    "printer",
    "stdio_server",
    "upgrade",
    "utility",
]
